### ISSUE TITLE
Not run application avalonia.mvvm

### ISSUE THREAD

**Issue by darksait88** [AvaloniaUI/avalonia-dotnet-templates#22]
**Description**

I get errors when trying to run an application created from the Avalonia template.

**Environment**
    OS: Ubuntu 18.04.02
    .NET Core: 2.2.202
    VS Code

**Steps**

1. Install avalonia-dotnet-templates
2. Create a new project: `dotnet new avalonia.mvvm`
3. `sudo dotnet run --framework netcoreapp2.1`

When I'm running dotnet run I get these errors:
```
Unhandled Exception: System.IO.FileNotFoundException: Unable to find view for ak_window.App
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 90
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj) in D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs:line 45
   at ak_window.App.Initialize() in /home/darksait88/Документы/ak_window/App.xaml.cs:line 10
   at Avalonia.Controls.AppBuilderBase`1.Setup() in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 302
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args) in D:\a\1\s\src\Avalonia.Controls\AppBuilderBase.cs:line 153
   at ak_window.Program.Main(String[] args) in /home/darksait88/Документы/ak_window/Program.cs:line 12
```

**Comment by kekekeks** [comment]
Unable to reproduce here with:
```
$ cat /etc/lsb-release |grep DES
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

$ dotnet --version
2.2.105
```
Please, try removing `bin` and `obj` and running without `sudo`

**Comment by darksait88** [comment]
The error did not disappear
I made a mistake in the specified version: .NET Core: 2.2.20**4**

**Comment by danwalmsley** [comment]
@darksait88 try removing the _ from you project name, does that help?

**Comment by kekekeks** [comment]
I think cyrillic characters (`Документы`) are the problem here. For some reason our MSBuild task is unable to get relative paths and generates garbage.

**Comment by kekekeks** [comment]
Moving the issue here https://github.com/AvaloniaUI/Avalonia/issues/2555

**Comment by darksait88** [comment]
> I think cyrillic characters in path (`Документы`) are the problem here. For some reason our MSBuild task is unable to get relative paths and generates garbage.

Thanks, it helped
